# Generated by Django 5.1.4 on 2024-12-17 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="게시글 제목", max_length=255)),
                ("content", models.TextField(help_text="게시글 본문")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BALLOON", "풍선/페이퍼아트"),
                            ("GIFT", "선물포장/보자기"),
                            ("WOOD", "목공/도자기/가죽"),
                            ("DIFFUSER", "디퓨터/캔들/석고방향제"),
                            ("RESIN", "레진/비즈공예"),
                            ("RATTAN", "라탄/마크라메"),
                            ("FLOWER", "플라워"),
                            ("TOTAL", "토탈공예"),
                        ],
                        help_text="게시글 카테고리",
                        max_length=20,
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, help_text="조회수"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, help_text="좋아요 수"),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, help_text="댓글 수"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("HIDDEN", "Hidden"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        help_text="게시글 상태",
                        max_length=20,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="삭제 여부 (True인 경우 삭제)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="작성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="이미지 URL (유효한 URL 형식)", max_length=2000
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="업로드 일시"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "db_table": "post_images",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="좋아요 생성 일시"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "post_likes",
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["category"], name="posts_categor_c9aadc_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["created_at"], name="posts_created_060265_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["is_deleted"], name="posts_is_dele_76d2f1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="postlike",
            unique_together={("post", "user")},
        ),
    ]
